
<HEAD>
<TITLE>DALL-E 2 Project</TITLE>
</HEAD>
<BODY BGCOLOR="FF6666">
<CENTER>
<H2>DALL-E 2</H2>
<p>OpenAI's groundbreaking model DALL-E 2 hit the scene at the beginning of the month, setting a new bar for image generation and manipulation. With only short text prompt, DALL-E 2 can generate completely new images that combine distinct and unrelated objects in semantically plausible ways, like the images below which were generated by entering the prompt "a bowl of soup that is a portal to another dimension as digital art".</p>
<img src="view.jpeg"/>
</CENTER>
</BODY>
</HTML>

